# Generated by Django 5.2.5 on 2025-10-13 15:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0001_initial'),
        ('site_settings', '0003_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('project_abstract', models.TextField(blank=True, null=True)),
                ('supervisor_request_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('None', 'None')], default='None', max_length=20)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['2nd Year Student', '3rd Year Student', '4th Year Student']}, related_name='student_batches', to='site_settings.dept_member')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Associate Professor', 'Assistant Professor', 'Professor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_batches', to='site_settings.dept_member')),
                ('supervisor_request_to', models.ForeignKey(blank=True, help_text='Faculty to whom the supervision request is currently sent.', limit_choices_to={'role__in': ['Associate Professor', 'Assistant Professor', 'Professor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_batches', to='site_settings.dept_member')),
            ],
        ),
        migrations.CreateModel(
            name='PRCMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batches', models.ManyToManyField(blank=True, related_name='prc_members', to='CSP.batch')),
                ('faculty', models.ForeignKey(limit_choices_to={'role__in': ['Associate Professor', 'Assistant Professor', 'Professor']}, on_delete=django.db.models.deletion.CASCADE, related_name='prc_memberships', to='site_settings.dept_member')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_batches', models.PositiveIntegerField(default=5, help_text='Number of batches the supervisor can guide.')),
                ('supervisor', models.OneToOneField(limit_choices_to={'role__in': ['Associate Professor', 'Assistant Professor', 'Professor']}, on_delete=django.db.models.deletion.CASCADE, related_name='slot_info', to='site_settings.dept_member')),
            ],
        ),
        migrations.DeleteModel(
            name='CSP',
        ),
    ]
