# Generated by Django 5.2.5 on 2025-10-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0002_batch_prcmember_supervisorslot_delete_csp'),
        ('site_settings', '0003_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='supervisor_request_status',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='supervisor_request_to',
        ),
        migrations.AddField(
            model_name='batch',
            name='request_status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='requested_supervisor',
            field=models.ForeignKey(blank=True, help_text='Faculty currently requested for supervision.', limit_choices_to={'role__in': ['Associate Professor', 'Assistant Professor', 'Professor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_requests', to='site_settings.dept_member'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Associate Professor', 'Assistant Professor', 'Professor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_batches', to='site_settings.dept_member'),
        ),
        migrations.AlterField(
            model_name='prcmember',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'role__in': ['Associate Professor', 'Assistant Professor', 'Professor']}, on_delete=django.db.models.deletion.CASCADE, related_name='prc_faculty', to='site_settings.dept_member'),
        ),
        migrations.CreateModel(
            name='SupervisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_requests', models.PositiveIntegerField(default=5, help_text='Maximum number of batches this faculty can guide.')),
                ('accepted_count', models.PositiveIntegerField(default=0, help_text='Number of accepted batches.')),
                ('supervisor', models.OneToOneField(limit_choices_to={'role__in': ['Associate Professor', 'Assistant Professor', 'Professor']}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_assignment', to='site_settings.dept_member')),
            ],
        ),
        migrations.DeleteModel(
            name='SupervisorSlot',
        ),
    ]
