# Generated by Django 5.2.5 on 2025-10-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0003_remove_batch_supervisor_request_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorassignment',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='requested_supervisor',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='PRCMember',
        ),
        migrations.DeleteModel(
            name='SupervisorAssignment',
        ),
    ]
