# Generated by Django 5.2.5 on 2025-10-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0004_remove_supervisorassignment_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='created_at',
        ),
    ]
