# Generated by Django 5.2.5 on 2025-10-13 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0005_remove_batch_created_at'),
        ('site_settings', '0003_alter_announcement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='project_domain',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='uid',
        ),
        migrations.AddField(
            model_name='batch',
            name='project_oneliner',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='project_abstract',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuideRequests', models.IntegerField(default=3)),
                ('faculty', models.ForeignKey(limit_choices_to={'role__in': ['HOD', 'Associate Professor', 'Assistant Professor', 'Professor']}, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='site_settings.dept_member')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='guide_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CSP.guide'),
        ),
        migrations.CreateModel(
            name='GuideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSP.batch')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSP.guide')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
