# Generated by Django 5.2.5 on 2025-10-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0006_remove_batch_project_domain_remove_batch_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiderequest',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='guiderequest',
            name='requested_by',
        ),
    ]
