# Generated by Django 5.2.5 on 2025-10-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0007_remove_guiderequest_requested_at_and_more'),
        ('site_settings', '0003_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiderequest',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='guide_assigned',
        ),
        migrations.RemoveField(
            model_name='guiderequest',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='project_abstract',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='project_oneliner',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='students',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_batches', to='site_settings.dept_member'),
        ),
        migrations.AddField(
            model_name='batch',
            name='members',
            field=models.ManyToManyField(related_name='student_batches', to='site_settings.dept_member'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='CSP.batch')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Professor', 'Associate Professor', 'Assistant Professor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.dept_member')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CSP.batch')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings.dept_member')),
            ],
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='GuideRequest',
        ),
    ]
