# Generated by Django 5.2.5 on 2025-10-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0008_remove_guiderequest_guide_and_more'),
        ('site_settings', '0003_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_batches', models.IntegerField(default=5)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role__in': ['Professor', 'Associate Professor', 'Assistant Professor']}, on_delete=django.db.models.deletion.CASCADE, to='site_settings.dept_member')),
            ],
        ),
    ]
