# Generated by Django 5.2.5 on 2025-10-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0009_supervisor_manage'),
        ('site_settings', '0003_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supervisor_manage',
            new_name='SupervisorManage',
        ),
        migrations.AlterModelOptions(
            name='supervisormanage',
            options={'verbose_name': 'Supervisor Management', 'verbose_name_plural': 'Supervisor Management'},
        ),
    ]
