# Generated by Django 5.2.5 on 2025-10-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0010_rename_supervisor_manage_supervisormanage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorrequest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSP.batch'),
        ),
    ]
