# Generated by Django 5.2.5 on 2025-10-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0011_alter_supervisorrequest_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorrequest',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CSP.batch'),
        ),
    ]
