# Generated by Django 5.2.5 on 2025-10-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0012_alter_supervisorrequest_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='pdf_report',
            field=models.URLField(blank=True, null=True),
        ),
    ]
