# Generated by Django 5.2.5 on 2025-10-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP', '0013_batch_pdf_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Targeted_Journals',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
