# Generated by Django 5.2.5 on 2025-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message1', models.TextField(blank=True, max_length=500, null=True, verbose_name='Message 1')),
                ('is_message1_active', models.BooleanField(default=False, verbose_name='Show Message 1')),
                ('message1_color', models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='green', max_length=10, verbose_name='Message 1 Color')),
                ('message2', models.TextField(blank=True, max_length=500, null=True, verbose_name='Message 2')),
                ('is_message2_active', models.BooleanField(default=False, verbose_name='Show Message 2')),
                ('message2_color', models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='orange', max_length=10, verbose_name='Message 2 Color')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='dept_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='downloadable_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteSettings', models.CharField(default='Site Settings', editable=False, max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('active_approval_letter', models.BooleanField(default=True, verbose_name='Allow Approval Letter Uploads')),
                ('active_undertaking_letter', models.BooleanField(default=True, verbose_name='Allow Undertaking Letter Uploads')),
                ('active_bonafide_letter', models.BooleanField(default=True, verbose_name='Allow Bonafide Letter Uploads')),
                ('max_students_per_internship', models.PositiveIntegerField(default=10, verbose_name='Max Students per Internship')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
