# Generated by Django 5.2.5 on 2025-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dept_member',
            options={'verbose_name': 'Department Member', 'verbose_name_plural': 'Department Members'},
        ),
        migrations.RemoveField(
            model_name='dept_member',
            name='department',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='active_approval_letter',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='active_bonafide_letter',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='active_undertaking_letter',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='max_students_per_internship',
        ),
        migrations.AddField(
            model_name='dept_member',
            name='Id_number',
            field=models.CharField(blank=True, help_text='Enter VTU/TTS Number', max_length=20, null=True, unique=True, verbose_name='VTU/TTS Number'),
        ),
        migrations.AddField(
            model_name='dept_member',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dept_member',
            name='role',
            field=models.CharField(blank=True, choices=[('2nd Year Student', '2nd Year Student'), ('3rd Year Student', '3rd Year Student'), ('4th Year Student', '4th Year Student'), ('HOD', 'HOD'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Lab Assistant', 'Lab Assistant'), ('Admin Staff', 'Admin Staff'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='max_students_per_batch',
            field=models.IntegerField(default=3, help_text='Set the maximum number of students allowed per internship batch.', verbose_name='Max Students per Internship'),
        ),
    ]
