# Generated by Django 5.2.5 on 2025-10-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_dept_member_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Site Announcement', 'verbose_name_plural': 'Site Announcements'},
        ),
        migrations.AlterModelOptions(
            name='downloadable_files',
            options={'verbose_name': 'Downloadable File', 'verbose_name_plural': 'Downloadable Files'},
        ),
    ]
