# Generated by Django 5.2.5 on 2025-10-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_member',
            name='catogry',
            field=models.CharField(blank=True, choices=[('CSP', 'CSP'), ('Minor 1', 'Minor 1'), ('Minor 2', 'Minor 2'), ('Major', 'Major'), ('Staff', 'Staff')], max_length=50, null=True),
        ),
    ]
