# Generated by Django 5.2.5 on 2025-10-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_dept_member_catogry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_member',
            name='reg_no',
            field=models.CharField(blank=True, help_text='Enter Registration Number', max_length=20, null=True, unique=True, verbose_name='Registration Number'),
        ),
    ]
